### ISSUE TITLE
Out of date leap second exception

### ISSUE THREAD

**Issue by bogdanni** [mbtaylor/jcdf#4] opened 2021-11-30 18:45 UTC
Last leap second was 2017-01-01, as of now (2021-11-30) the library raises the exception below with the attached file, even though it does include an up-to-date leap second list.
```
Exception in thread "main" java.lang.RuntimeException: CDF TIME_TT2000 date formatting failed - library leap second table known to be out of date with respect to data. Update CDF_LEAPSECONDSTABLE environment variable to point at file http://cdf.gsfc.nasa.gov/html/CDFLeapSeconds.txt
	at uk.ac.bristol.star.cdf.EpochFormatter.formatTimeTt2000(EpochFormatter.java:175)
	at uk.ac.bristol.star.cdf.DataType$Tt2kDataType.formatArrayValue(DataType.java:487)
	at uk.ac.bristol.star.cdf.util.CdfList.formatValues(CdfList.java:138)
	at uk.ac.bristol.star.cdf.util.CdfList.run(CdfList.java:112)
	at uk.ac.bristol.star.cdf.util.CdfList.runMain(CdfList.java:225)
	at uk.ac.bristol.star.cdf.util.CdfList.main(CdfList.java:233)
```
[solo_L2_mag-rtn-normal-1-minute_20201107_V02.cdf.gz](https://github.com/mbtaylor/jcdf/files/7628034/solo_L2_mag-rtn-normal-1-minute_20201107_V02.cdf.gz)

**Comment by mbtaylor** [comment] 2021-11-30 20:40
I can reproduce this and will look into it.  In the mean time you should be able to avoid this exception if you want to by setting the static variable `uk.ac.bristol.star.cdf.EpochFormatter.FAIL_ON_LEAP_ERROR` to `false`.

**Comment by mbtaylor** [comment] 2021-12-01 17:22
Should be fixed by 55491285b.  Thanks for the report.

**Comment by bogdanni** [comment] 2021-12-02 10:19
Works for me now. Thank you for all the software!

**Comment by mbtaylor** [comment] 2021-12-02 12:14
Great.  I'll make a numbered release with these fixes at some point.  However it looks like you're still running into issues, so I'll give it a while in case more things come up.  If you are or are not expecting to continue testing this over some known period, let me know.

**Closed as completed by mbtaylor** 2021-12-02 12:14 UTC

**Comment by bogdanni** [comment] 2021-12-02 12:30
Please allow until the end of next week to test against a collection of various files.

**Comment by mbtaylor** [comment] 2021-12-02 12:37
Happy to do that.  Any more problems or queries, raise an issue.

**Comment by bogdanni** [comment] 2021-12-10 09:20
I haven't encountered other issues yet. Will open new reports in case. Thank you for the software.

**Comment by mbtaylor** [comment] 2021-12-10 09:22
Thanks @bogdanni, appreciated.  I will probably issue a new release in the coming days.

**Comment by mbtaylor** [comment] 2021-12-15 17:16
New bugfix release 1.2-4 is now available.
